version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/bookingappdb
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookingappdb
    ports:
      - "5433:5432"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
