"""update review mode

Revision ID: 2ae3ea4678b6
Revises: 3a5568cc687a
Create Date: 2026-09-13 09:38:05.118950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae3ea4678b6'
down_revision: Union[str, Sequence[str], None] = '3a5568cc687a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_watched_user_movie', 'watched', ['user_id', 'movie_id'])
    op.drop_constraint(op.f('watched_movie_id_fkey'), 'watched', type_='foreignkey')
    op.drop_constraint(op.f('watched_user_id_fkey'), 'watched', type_='foreignkey')
    op.create_foreign_key(None, 'watched', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watched', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('watchlist_movie_id_fkey'), 'watchlist', type_='foreignkey')
    op.drop_constraint(op.f('watchlist_user_id_fkey'), 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key(op.f('watchlist_user_id_fkey'), 'watchlist', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('watchlist_movie_id_fkey'), 'watchlist', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'watched', type_='foreignkey')
    op.drop_constraint(None, 'watched', type_='foreignkey')
    op.create_foreign_key(op.f('watched_user_id_fkey'), 'watched', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('watched_movie_id_fkey'), 'watched', 'movies', ['movie_id'], ['id'])
    op.drop_constraint('uq_watched_user_movie', 'watched', type_='unique')
    # ### end Alembic commands ###
