"""update relation model

Revision ID: 3a5568cc687a
Revises: dbb8cf4a4d37
Create Date: 2026-09-12 17:42:24.907394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5568cc687a'
down_revision: Union[str, Sequence[str], None] = 'dbb8cf4a4d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_watched_user_movie'), 'watched', type_='unique')
    op.drop_constraint(op.f('watched_movie_id_fkey'), 'watched', type_='foreignkey')
    op.drop_constraint(op.f('watched_user_id_fkey'), 'watched', type_='foreignkey')
    op.create_foreign_key(None, 'watched', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'watched', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched', type_='foreignkey')
    op.drop_constraint(None, 'watched', type_='foreignkey')
    op.create_foreign_key(op.f('watched_user_id_fkey'), 'watched', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('watched_movie_id_fkey'), 'watched', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_watched_user_movie'), 'watched', ['user_id', 'movie_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
