"""movie created model UPDATED

Revision ID: dc34edb53eda
Revises: dddaffbdf861
Create Date: 2025-07-26 21:55:58.254826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc34edb53eda'
down_revision: Union[str, Sequence[str], None] = 'dddaffbdf861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_movie_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genere', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('movie_id', name=op.f('movies_pkey')),
    sa.UniqueConstraint('image_url', name=op.f('movies_image_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('title', name=op.f('movies_title_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_movies_movie_id'), 'movies', ['movie_id'], unique=False)
    # ### end Alembic commands ###
