"""initial_revision

Revision ID: f5a4b942e239
Revises: 3e7e9591015d
Create Date: 2026-09-12 17:31:53.702651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a4b942e239'
down_revision: Union[str, Sequence[str], None] = '3e7e9591015d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_watched_user_movie')
    )
    op.create_index(op.f('ix_watched_id'), 'watched', ['id'], unique=False)
    op.create_index(op.f('ix_watched_movie_id'), 'watched', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watched_user_id'), 'watched', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_user_id'), table_name='watched')
    op.drop_index(op.f('ix_watched_movie_id'), table_name='watched')
    op.drop_index(op.f('ix_watched_id'), table_name='watched')
    op.drop_table('watched')
    # ### end Alembic commands ###
